### ISSUE TITLE
Dark mode toggle disabled when a graph is shown (if intended, there should be an indication to the user about it when trying to toggle)

### ISSUE THREAD

**Issue by RandyHuynh5815** [icssc-projects/Zotistics#10]

**Comment by patrickanguyen** [comment]
The reason for this issue is the `search-content-wrapper` div, which is displayed when a graph is shown, overlaps with the `dog` div, which makes the `dog` div unselectable. 

The `dog` div is still selectable at the bottom, where the `search-content-wrapper` does not overlap with the `dog` div.

![image](https://user-images.githubusercontent.com/41417417/145706046-7e3177d0-fabc-4082-9f27-56ff5f3c6300.png)
